api = "0.10"

WithWindowsBuild = false
WithLinuxBuild = false

[buildpack]
id = "flagcatstudio/shaka-packager-buildpack"
name = "shaka-packager-buildpack"
version = "0.0.2"

[[stacks]]
  id = "*"

[[targets]]
  os = "linux"
  arch = "amd64"
