api = "0.10"

WithWindowsBuild = false
WithLinuxBuild = false

[buildpack]
id = "github.com/flagcatstudio/shaka-packager-buildpack"
name = "shaka-packager-buildpack"
version = "0.0.2"

# Targets the buildpack will work with
[[targets]]
  os = "linux"
  arch = "amd64"
